### ISSUE TITLE
mcmc_joy function for joy plots

### ISSUE THREAD

**Issue by jgabry** [stan-dev/bayesplot#104]
As an alternative to `mcmc_areas`, provide an `mcmc_joy` function for making joy plots (see @tjmahr 's https://rpubs.com/tjmahr/joyplot for example). Perhaps the implementation can be done easily by making use of the nice **ggjoy** package by @clauswilke. 

In terms of organization/doc, I guess this function could be included in the `MCMC-intervals` category with `mcmc_intervals` and `mcmc_areas`.

**Comment by tjmahr** [comment]
I started functions to do `mcmc_dens` and `mcmc_dens_overlay` with joyplots. 

![jp1](https://user-images.githubusercontent.com/1890315/30069718-1a08aa4a-9227-11e7-8ec2-e9cf259064a8.png)

![jp0](https://user-images.githubusercontent.com/1890315/30069705-145b2e38-9227-11e7-8090-41e396e6b6a6.png)




1. What should we call these functions? `joydens`?
2. Should we have a horizontal guide lines?
3. The joyplot theme tweaks the y-axis text so the they text sits just above the ticks. Is this something we want to do?

![image](https://user-images.githubusercontent.com/1890315/30069507-86253f64-9226-11e7-880a-b2c6ef9c047a.png)

**Comment by jgabry** [comment]
Cool! In terms of naming the functions, maybe`mcmc_joydens` is fine. Could also just go with  `mcmc_joy`. Do you have a preference?

**Comment by jgabry** [comment]
As for your questions 2 and 3 I don't have a strong opinion so go with what you think is best for now.

**Comment by tjmahr** [comment]
Hmm, I want to save `mcmc_joy` for the implementation that works like(/replaces?) `mcmc_areas`. These are just plotting the density interval `c(0,1)`.  `mcmc_joy` would be more like what I played with in the Rpubs [proof of concept](https://rpubs.com/tjmahr/joyplot).

Also, I need to think about making the outline thicker or have a better contrast when the density curves pile on top of each other.

**Comment by jgabry** [comment]
Ok yeah saving the name `mcmc_joy` for that makes sense.

**Comment by tjmahr** [comment]
I also just want to note that [this is also a really good write up](https://mikedecr.github.io/2017/07/25/joy-of-bayes/) on using joyplots for Bayesian models written around the same time that I did my proof of concept. It documents why we have to compute the density manually when making these plots.

**Comment by clauswilke** [comment]
All,

a couple of comments:

1. There have been talks about moving away from the name "joyplot", due to the underlying history of the term (see [here](https://en.wikipedia.org/wiki/House_of_Dolls)). I will likely rename ggjoy to something else sometime this fall. So maybe not use `mcmc_joy`. You could use `mcmc_ridgelines` or `mcmc_ridgedensities`.

2. Regarding the criticism of long tails in `stat_joy`, please realize that I put this together in a few hours and by no means mean to imply it's perfect or final. Instead of recommending manual recalculation of the densities, I think the right approach would be to either improve `stat_joy` (e.g. by adding appropriate options for the density calculation) or to implement a separate stat for mcmc chains. I'm happy to give advice on how to do this, it's not difficult at all.

Best, 
  Claus

**Comment by jgabry** [comment]
@clauswilke Thanks for the comments! 

1. Wow, I can definitely see the motivation for moving away from that name given the history (I was not aware of that). 

2. Totally understand that the package is still in its infancy. It's a great start! It would definitely be preferable not to have to manually recalculate the densities, so if `stat_joy` (or whatever the eventual name is) could take of this that would be great. @tjmahr What do you think?

**Comment by betanalpha** [comment]
I agree about the name — can we just abandon it entirely and start calling it a Craft plot via its source, https://blogs.scientificamerican.com/sa-visual/pop-culture-pulsar-origin-story-of-joy-division-s-unknown-pleasures-album-cover-video/? <https://blogs.scientificamerican.com/sa-visual/pop-culture-pulsar-origin-story-of-joy-division-s-unknown-pleasures-album-cover-video/?>  It will cause confusion but hopefully that confusion will induce some useful conversations.

**Comment by tjmahr** [comment]
@clauswilke. Good point about the name. I'm going with ridge/ridgeline. 

* mcmc_dens_ridges (+ mcmc_dens_ridge_data)
* mcmc_dens_ridges_chains  (+ mcmc_dens_ridges_chains_data)
* mcmc_ridges (mcmc_ridges_data, for the interval plot like mcmc_areas)

@jgabry Hmm, so the reason why we manual compute the density is because the geom_joy uses the whole x-axis. 

![image](https://user-images.githubusercontent.com/1890315/30077000-085fb158-9240-11e7-9aa9-d54a3e73e5fa.png)

It's a very aesthetically pleasing default, but we don't want to draw parameter values that are not part of a model's MCMC samples. I don't mean at all to criticize ggjoy. It's just that we don't want to plot zero density values. (And to be fair, using `geom_joy(..., rel_min_height = .001)` gets close to what we want.)

For now, it's simpler if we manually compute the densities. It's not that difficult. We still use geom_joy to vertically scale and plot the ridgelines. Plus, with the package's new convention of providing `_data()` functions that return the data that would be plotted by a plotting function, we have to do the manual calculation anyway in order to give users the density values.

**Comment by jgabry** [comment]
@tjmahr good points. What you outline seems fine to me.

**Comment by clauswilke** [comment]
FYI, I made this now: https://github.com/clauswilke/ggridges

Still need to verify that everything is correct and then I'll go ahead and submit to CRAN, probably within about a week.

**Comment by jgabry** [comment]
@clauswilke Great. Thank you for letting us know!

**Comment by clauswilke** [comment]
This exists now:
https://cran.r-project.org/web/packages/ggridges/index.html

Please don't advertise yet, I'm going to make a proper announcement within the next few days.

**Comment by clauswilke** [comment]
The new package is now officially announced:
http://serialmentor.com/blog/2017/9/15/goodbye-joyplots

As of today, the ggjoy package on CRAN simply loads ggridges and re-exports some functions under their old names. There is no functional difference between the two packages.

**Comment by tjmahr** [comment]
I'm thinking of doing `mcmc_areas_ridges()` as a streamlined version of `mcmc_areas()` but optimized for random effects kinds of things.

* No rhat coloring
* No point estimates
* Overlapping densities
* Horizontal gridlines
* Tweak y axis text to line up with the horizontal gridlines

## intervals coloring

```r
m <- shinystan::eight_schools@posterior_sample
mcmc_areas_ridges(m, pars = "mu", regex_pars = "theta") + 
  ggtitle("Treatment effect on eight schools (Rubin, 1981)")
```
![8a](https://user-images.githubusercontent.com/1890315/30862090-80dddb48-a292-11e7-90ea-0fb7f3cca6fd.png)

```r
mcmc_areas_ridges(m, pars = "mu", regex_pars = "theta", 
                 fill_width = .8, interval_width = .95) + 
  ggtitle("Treatment effect on eight schools (Rubin, 1981)")
```
![8b](https://user-images.githubusercontent.com/1890315/30862153-b702341c-a292-11e7-916f-8518bfc044d8.png)
