### ISSUE TITLE
mcmc_pairs() + plot_bg() yields a NULL

### ISSUE THREAD

**Issue by ASKurz** [stan-dev/bayesplot#128]
I have a handful of posterior parameters I’d like to put in a pairs plot. By itself, `mcmc_pairs()` works great. E.g., 

```{r}
posterior <- tibble(x = rnorm(1e3, 0, 1),
                    y = rnorm(1e3, 0, 1),
                    z = rnorm(1e3, 0, 1))
                    
mcmc_pairs(x = posterior,
           pars = c("x", "y", "z"))
```

I’d like to change my background fill. But when I try to use ` plot_bg()`, I get a NULL.

```{r}
mcmc_pairs(x = posterior,
           pars = c("x", "y", "z")) +
  plot_bg(fill = "grey85",
          color = "transparent")
```

Yet, ` plot_bg()` works just fine with `mcmc_scatter().` E.g., 

```{r}
mcmc_scatter(x = posterior,
             pars = c("x", "y")) +
  plot_bg(fill = "grey85",
          color = "transparent")
```

What am I missing?

**Comment by jgabry** [comment]
I think this is because `mcmc_pairs` unfortunately returns a grid of different ggplot objects plots instead of a single ggplot object (almost all of the other functions return a single ggplot object). It wasn't possible (at least it didn't seem possible when we tried) to get the plot how we wanted it to look without creating separate plots and combining them in a grid like that.

To get around this problem you can try updating the theme before making the plot, e.g:

```r
library(bayesplot)
library(ggplot2)

# set theme to default bayesplot theme but modify background
my_background <- element_rect(fill = "grey85", color = "transparent") 
theme_set(theme_default() + theme(plot.background = my_background))

# then call mcmc_pairs after updating the theme
mcmc_pairs(...)
```

Does that make the plot you were wanting?

**Comment by jgabry** [comment]
Actually you can just do 

```r
theme_set(theme_default() + plot_bg(fill = "grey85", color = "transparent"))
```

**Comment by ASKurz** [comment]
That’s instructive. Yes, both methods work great. Thanks jgabry!

**Comment by jgabry** [comment]
No problem, glad that worked!
