### ISSUE TITLE
Bayesplot appears to not plot vlines outside of existing draws

### ISSUE THREAD

**Issue by singmann** [stan-dev/bayesplot#135]
I want to plot a `vline` in an area of the plot that has no samples. However, using `vline_at()` (or for that matter `geom_vline()`) the line is not drawn. It works if I move the line further to the left (in the following example).

```
library(bayesplot)
x <- example_mcmc_draws(params = 6)
color_scheme_set("brightblue")
mcmc_intervals(x) + 
  ggplot2::coord_cartesian(xlim = c(-50, 100)) +
  vline_at(v = 90)
```

Which gives:
![rplot](https://user-images.githubusercontent.com/1902102/37230655-94fe4b8a-23e8-11e8-9815-06329c1f15e0.png)

**Comment by tjmahr** [comment]
After some troubleshooting, I determined that it's because `mcmc_intervals()` uses `xlim()` internally, so that needs to be updated to included the selected value.

This fails...

```r
library(ggplot2)
library(bayesplot)
x <- example_mcmc_draws(params = 6)
mcmc_intervals(x) + 
  vline_at(v = (-5:10) * 10, color = "pink", size = 2) +
  coord_cartesian(xlim = c(-50, 100))
```

![image](https://user-images.githubusercontent.com/1890315/37231185-d9b90064-23af-11e8-85a6-25e436821be7.png)

But updating `xlim()` works.

```r
last_plot() + 
  xlim(c(-50, 100))
#> Scale for 'x' is already present. Adding another scale for 'x', which will replace the existing scale.
```

![image](https://user-images.githubusercontent.com/1890315/37231225-03b2e86c-23b0-11e8-8499-e0fca013b3de.png)

**Comment by singmann** [comment]
Thanks for the quick response.
