### ISSUE TITLE
mcmc_trace: start iteration counting after warmup

### ISSUE THREAD

**Issue by paul-buerkner** [stan-dev/bayesplot#14]
This requires a column in the data.frame / matrix that enumerates the iterations (e.g. beginning with 1001, if 1000 warmup samples were used).

**Comment by jgabry** [comment]
@paul-buerkner What about instead of requiring an addition column in the data frame there was an argument (maybe `iter1` or something like that) that could be used to specify the iteration number of the first included draw? Then `mcmc_trace` would just label the iterations sequentially starting with `iter1`.

**Comment by paul-buerkner** [comment]
Sounds good! It's only a minor issue though.
