### ISSUE TITLE
ggplot2::theme_set does not always override bayesplot theme

### ISSUE THREAD

**Issue by jgabry** [stan-dev/bayesplot#158]
@malcolmbarrett After merging the PR I was playing around with some plots and I just noticed something strange that I had missed when reviewing the PR. Here's an example: 

```r
library(bayesplot)
library(ggplot2)

x <- example_mcmc_draws()

# plot using bayesplot default theme
mcmc_hist(x)  

# plot using theme_minimal
theme_set(theme_minimal())
mcmc_hist(x)

# should plot using theme_minimal but instead uses bayesplot theme_default
mcmc_hist(x) 
```

I was expecting the third call to `mcmc_hist` to also use `theme_minimal` but somehow it switches back to using the bayesplot default theme. Do you get the same behavior? If I use `bayesplot_theme_set` to set `theme_minimal` then all subsequent plots use `theme_minimal` as expected but when I use regular `theme_set` only the first time I make the plot does it use `theme_minimal`.

**Comment by malcolmbarrett** [comment]
Oops! It's not actually saving the ggplot2 theme as the current bayesplot theme. I'll send a PR momentarily that works as you describe here (certainly the expected behavior)

**Comment by malcolmbarrett** [comment]
Although, now that I say it, it makes less sense for the vignettes to use theme_default() without explicitly calling it since rstanarm will no longer change the default plot.

**Comment by jgabry** [comment]
@malcolmbarrett Actually I think there's still an issue: 

```r
# restart session and then: 

theme_set(theme_dark())
bayesplot_theme_set(theme_minimal())

mcmc_hist(x) # uses theme_minimal as expected

theme_set(theme_dark())
mcmc_hist(x) # still uses theme_minimal
```

That last plot should be using `theme_dark` right?

**Comment by malcolmbarrett** [comment]
Yes, right now, if you use this sequence, `bayesplot_theme_get()` can't tell that anything has changed (it saves the most recent `theme_get()` it has seen , which is still `theme_dark`, so it doesn't look different). You'd have to use `bayesplot_theme_set()` or set a different theme with `theme_set()`.

I don't think this is a very likely use-case, but I guess you never know. Unfortunately, I can't think of anything off the top of my head to fix it. Maybe a local version of `theme_set()` that just does what the ggplot version does and then also updates the internal bayesplot theme? I don't usually like it when packages do that, though, so that seems like a bad solution for an unlikely bug.

**Comment by jgabry** [comment]
Ok I see what you mean. Not a huge deal.
