### ISSUE TITLE
random warning on unit test

### ISSUE THREAD

**Issue by tjmahr** [stan-dev/bayesplot#186]
*Sometimes* I get the following warning when running tests

```
test-ppc-test-statistics.R:30: warning: ppc_stat returns ggplot object
Computation failed in `stat_bin()`:
`binwidth` must be positive
```
The specific test is 

```
  expect_gg(ppc_stat(y2, yrep2, stat = "prop0"))
```

But this doesn't happen every time. We need to bin down this nondeterminism.

**Comment by jgabry** [comment]
I haven't seen that before, but my first guess is that this is because the seed for generating the data is set on line 9 instead of line 1:

https://github.com/stan-dev/bayesplot/blob/b27d9b72b7c1f9e42a1b871c9951aba5545b749e/tests/testthat/data-for-ppc-tests.R#L5-L12

(Same issue with the script generating the data for the MCMC plot tests. )

I can't be sure this is the problem because I haven't seen that error, but either way we should probably be setting the seed before simulating data for the tests. I thought we were, but I guess not. Sorry about that.

**Comment by jgabry** [comment]
Alternatively, we could save the data for these tests in an rds or rda file and just load it in.

**Comment by jgabry** [comment]
Ok so this is related to https://github.com/tidyverse/ggplot2/issues/3043 and is fixed by https://github.com/tidyverse/ggplot2/pull/3047. In d5bd1a8 I've also added a seed when we generate data for the tests. 

I think it's safe to close this now.
