### ISSUE TITLE
ppc ribbon with points for observations

### ISSUE THREAD

**Issue by charlesm93** [stan-dev/bayesplot#256]
Per the discussion on https://discourse.mc-stan.org/t/bayesplot-ppc-ribbon-using-points-for-observations/19599, it'd be nice to have a ppc plot which uses a ribbon for the model predictions but points for the observations.

I propose adding an argument to the function `ppc_ribbon` and `ppc_ribbon_grouped`, namely `y_is_point` which defaults to FALSE (so as to not break backward compatibility). So the signature would be

```
ppc_ribbon(
  y,
  yrep,
  x = NULL,
  ...,
  prob = 0.5,
  prob_outer = 0.9,
  alpha = 0.33,
  size = 0.25,
  y_is_point = FALSE
)
```

I can build this feature in.

**Comment by jgabry** [comment]
Thanks Charles, I'm in favor of this. Regarding the argument, in the `ppc_violin_grouped()` function we currently have an argument `y_draw` with three options `y_draw="violin"`,  `y_draw="points"` or `y_draw="both"`. Could we just do the same here but the first option is `"line"` instead of `"violin"`?

**Comment by charlesm93** [comment]
Sure thing. I'll have `y_draw` default to "line".

**Comment by jgabry** [comment]
closing this since we merged the PR already
