### ISSUE TITLE
Different rhat for Rstan and CmdStanR

### ISSUE THREAD

**Issue by Alex-Cremers** [stan-dev/bayesplot#286]
Hello,

I have a model fitted with cmdstanR which did not converge properly. The Rhat for one of the parameters is 1.33 when I look at `model_fit$summary()`, however if turn the model into a stanfit object, the summary now indicates a Rhat of 1.48.

I first thought that the two summary functions call different `rhat` functions, but the following lines do show the same discrepancy:
```{r}
bayesplot::rhat(model_fit,pars="alpha")
rstan_fit = rstan::read_stan_csv(model_fit$output_files())
bayesplot::rhat(rstan_fit,pars="alpha")
```

Is there a reason why this could happen, or it it a bug? If needed I can upload the draws for this particular parameter. Using `posterior::rhat` on the matrix of draws returns 1.33, as with the summary method for the CmdStanFit object.

Best regards,

**Comment by jgabry** [comment]
Hi @Alex-Cremers, sorry nobody responded until now! 

Internally `bayesplot::rhat` uses the values computed by CmdStanR and RStan (bayesplot doesn't actually compute anything itself), so the issue is that CmdStanR's summary method is using `posterior`'s Rhat whereas RStan's summary method is still using the older version of Rhat. After you convert `model_fit` to `rstan_fit` the Rhat values that are used will come from RStan's summary method and will be different. 

Sorry again for the (very) slow reply!
