### ISSUE TITLE
validate_y does not accept ts objects

### ISSUE THREAD

**Issue by helske** [stan-dev/bayesplot#92]
Would it be possible to relax conditions of the `validate_y` function so that it would also accept univariate time series objects (and maybe also other objects which are essentially numeric vectors)? Currently if I want to use for example `ppc_intervals` I first need to convert my data with `as.numeric` which is bit annoying.

**Comment by helske** [comment]
Also in case of time series it would make sense to have default `x` as `time(x)`. But, I just realized there is a generic function for predictive checks, so in my case I think I will construct own method for the output of `walker` package.

**Comment by jgabry** [comment]
Sorry for the delay getting back to you. I agree it's kind of annoying to have to call `as.numeric` in this case. Defining your own method for the generic `pp_check` function (as you suggested in your second message) is one option (since you can do the `as.numeric` internally then), but I'm open to relaxing the checks in the `validate_y` function. The reason I made it pretty strict is that I wanted to avoid users passing in objects of arbitrary classes that may or may not result in unexpected behavior. 

Is defining a `pp_check` method sufficient for you or would it be helpful to change `validate_y`?

**Comment by helske** [comment]
Currently I solved the issue with own methods etc, but I think it would still be helpful to change `validate_y`. Also, similar change would be useful in `validate_x`: If the `y` argument is (univariate) `ts` object, the default `x` should be the time indices of `y` instead of `1:length(y)`.

**Comment by jgabry** [comment]
Closing this now that PR #94 is merged. Thanks!
